CREATE DATABASE TEST;

CREATE TABLE users (
id INT (11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
login VARCHAR (30) NOT NULL,
user_password VARCHAR (30) NOT NULL,
user_name VARCHAR (255) NOT NULL,
user_email VARCHAR (255) NOT NULL,
create_date DATETIME NOT NULL
);