CREATE DATABASE test;

GRANT ALL PRIVILEGES ON test.* TO `fedyaka`@`%` IDENTIFIED BY 'NS9%ugWvk3';

USE test;

CREATE TABLE users (
  id INT (11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  login VARCHAR (30) NOT NULL,
  user_password VARCHAR (30) NOT NULL,
  user_name VARCHAR (255) NOT NULL,
  user_email VARCHAR (255) NOT NULL,
  create_date DATETIME NOT NULL
);

CREATE TABLE user_groups (
id SERIAL PRIMARY KEY,
group_name VARCHAR(30) NOT NULL
);

CREATE TABLE user_groups_users_relations (
user_id BIGINT UNSIGNED NOT NULL,
group_id BIGINT UNSIGNED NOT NULL
);
